-- #################### TABLE CONTACT #######################
CREATE TABLE CONTACT
(
  ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (ID),
  NAME VARCHAR(255) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP,
  VERSION INT NOT NULL
);

ALTER TABLE CONTACT
    ADD INDEX INDEX_NAME_CONTACT (NAME);



-- #################### TABLE MAIL #######################
CREATE TABLE MAIL
(
  ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (ID),
  MAIL VARCHAR(255) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP NOT NULL,
  VERSION INT NOT NULL
);

ALTER TABLE MAIL
    ADD INDEX INDEX_MAIL_MAIL (MAIL);

ALTER TABLE MAIL
    ADD CONTACT_ID INT UNSIGNED NOT NULL DEFAULT 0;

ALTER TABLE MAIL
    ADD CONSTRAINT FK_ID_CONTACT FOREIGN KEY (CONTACT_ID) REFERENCES CONTACT(ID);

ALTER TABLE MAIL
    ADD INDEX INDEX_FK_ID_CONTACT (CONTACT_ID);


