-- #################### TABLE MAIL #######################
CREATE TABLE MAIL
(
  ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (ID),
  MAIL VARCHAR(255) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP NOT NULL,
  VERSION INT NOT NULL
);

ALTER TABLE MAIL
    ADD INDEX INDEX_MAIL_MAIL (MAIL);



-- #################### TABLE CONTACT #######################
CREATE TABLE CONTACT
(
  ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (ID),
  NAME VARCHAR(255) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP,
  VERSION INT NOT NULL
);

ALTER TABLE CONTACT
    ADD INDEX INDEX_NAME_CONTACT (NAME);

ALTER TABLE CONTACT
    ADD MAIL_ID INT UNSIGNED NOT NULL DEFAULT 0;

ALTER TABLE CONTACT
    ADD CONSTRAINT FK_ID_MAIL FOREIGN KEY (MAIL_ID) REFERENCES MAIL(ID);

ALTER TABLE CONTACT
    ADD INDEX INDEX_FK_ID_MAIL (MAIL_ID);
